import configparser

dictionary = configparser.ConfigParser()
dictionary.read("dictionary_file.dict", "utf-8")


def connect_keyboard_button(self):
    keyboard = self.main_keyboard.ki
    
    keyboard.btn_a.clicked.connect(lambda: self.keyboard_print(keyboard.btn_a.text()))
    keyboard.btn_i.clicked.connect(lambda: self.keyboard_print(keyboard.btn_i.text()))
    keyboard.btn_u.clicked.connect(lambda: self.keyboard_print(keyboard.btn_u.text()))
    keyboard.btn_e.clicked.connect(lambda: self.keyboard_print(keyboard.btn_e.text()))
    keyboard.btn_o.clicked.connect(lambda: self.keyboard_print(keyboard.btn_o.text()))
    keyboard.btn_ka.clicked.connect(lambda: self.keyboard_print(keyboard.btn_ka.text()))
    keyboard.btn_ki.clicked.connect(lambda: self.keyboard_print(keyboard.btn_ki.text()))
    keyboard.btn_ku.clicked.connect(lambda: self.keyboard_print(keyboard.btn_ku.text()))
    keyboard.btn_ke.clicked.connect(lambda: self.keyboard_print(keyboard.btn_ke.text()))
    keyboard.btn_ko.clicked.connect(lambda: self.keyboard_print(keyboard.btn_ko.text()))
    keyboard.btn_sa.clicked.connect(lambda: self.keyboard_print(keyboard.btn_sa.text()))
    keyboard.btn_shi.clicked.connect(lambda: self.keyboard_print(keyboard.btn_shi.text()))
    keyboard.btn_su.clicked.connect(lambda: self.keyboard_print(keyboard.btn_su.text()))
    keyboard.btn_se.clicked.connect(lambda: self.keyboard_print(keyboard.btn_se.text()))
    keyboard.btn_so.clicked.connect(lambda: self.keyboard_print(keyboard.btn_so.text()))
    keyboard.btn_ta.clicked.connect(lambda: self.keyboard_print(keyboard.btn_ta.text()))
    keyboard.btn_chi.clicked.connect(lambda: self.keyboard_print(keyboard.btn_chi.text()))
    keyboard.btn_tsu.clicked.connect(lambda: self.keyboard_print(keyboard.btn_tsu.text()))
    keyboard.btn_te.clicked.connect(lambda: self.keyboard_print(keyboard.btn_te.text()))
    keyboard.btn_to.clicked.connect(lambda: self.keyboard_print(keyboard.btn_to.text()))
    keyboard.btn_na.clicked.connect(lambda: self.keyboard_print(keyboard.btn_na.text()))
    keyboard.btn_ni.clicked.connect(lambda: self.keyboard_print(keyboard.btn_ni.text()))
    keyboard.btn_nu.clicked.connect(lambda: self.keyboard_print(keyboard.btn_nu.text()))
    keyboard.btn_ne.clicked.connect(lambda: self.keyboard_print(keyboard.btn_ne.text()))
    keyboard.btn_no.clicked.connect(lambda: self.keyboard_print(keyboard.btn_no.text()))
    keyboard.btn_ha.clicked.connect(lambda: self.keyboard_print(keyboard.btn_ha.text()))
    keyboard.btn_hi.clicked.connect(lambda: self.keyboard_print(keyboard.btn_hi.text()))
    keyboard.btn_fu.clicked.connect(lambda: self.keyboard_print(keyboard.btn_fu.text()))
    keyboard.btn_he.clicked.connect(lambda: self.keyboard_print(keyboard.btn_he.text()))
    keyboard.btn_ho.clicked.connect(lambda: self.keyboard_print(keyboard.btn_ho.text()))
    keyboard.btn_ma.clicked.connect(lambda: self.keyboard_print(keyboard.btn_ma.text()))
    keyboard.btn_mi.clicked.connect(lambda: self.keyboard_print(keyboard.btn_mi.text()))
    keyboard.btn_mu.clicked.connect(lambda: self.keyboard_print(keyboard.btn_mu.text()))
    keyboard.btn_me.clicked.connect(lambda: self.keyboard_print(keyboard.btn_me.text()))
    keyboard.btn_mo.clicked.connect(lambda: self.keyboard_print(keyboard.btn_mo.text()))
    keyboard.btn_ya.clicked.connect(lambda: self.keyboard_print(keyboard.btn_ya.text()))
    keyboard.btn_yu.clicked.connect(lambda: self.keyboard_print(keyboard.btn_yu.text()))
    keyboard.btn_yo.clicked.connect(lambda: self.keyboard_print(keyboard.btn_yo.text()))
    keyboard.btn_wa.clicked.connect(lambda: self.keyboard_print(keyboard.btn_wa.text()))
    keyboard.btn_n.clicked.connect(lambda: self.keyboard_print(keyboard.btn_n.text()))
    keyboard.btn_ra.clicked.connect(lambda: self.keyboard_print(keyboard.btn_ra.text()))
    keyboard.btn_ri.clicked.connect(lambda: self.keyboard_print(keyboard.btn_ri.text()))
    keyboard.btn_ru.clicked.connect(lambda: self.keyboard_print(keyboard.btn_ru.text()))
    keyboard.btn_re.clicked.connect(lambda: self.keyboard_print(keyboard.btn_re.text()))
    keyboard.btn_ro.clicked.connect(lambda: self.keyboard_print(keyboard.btn_ro.text()))
    keyboard.btn_dash.clicked.connect(lambda: self.keyboard_print(keyboard.btn_dash.text()))

    keyboard.btn_mark.clicked.connect(self.add_sound_mark)
    keyboard.btn_small.clicked.connect(self.change_letter_size)
    keyboard.btn_kana.clicked.connect(self.main_keyboard.change_kana)
    keyboard.btn_search.clicked.connect(self.start_search)
    keyboard.btn_backspace.clicked.connect(self.backspace)
    keyboard.btn_clear.clicked.connect(self.clear_search_input)


def set_keyboard_kana(self, kana: str):
    if kana == "katakana":
        self.ki.btn_a.setText("ア")
        self.ki.btn_i.setText("イ")
        self.ki.btn_u.setText("ウ")
        self.ki.btn_e.setText("エ")
        self.ki.btn_o.setText("オ")
        self.ki.btn_ka.setText("カ")
        self.ki.btn_ki.setText("キ")
        self.ki.btn_ku.setText("ク")
        self.ki.btn_ke.setText("ケ")
        self.ki.btn_ko.setText("コ")
        self.ki.btn_sa.setText("サ")
        self.ki.btn_shi.setText("シ")
        self.ki.btn_su.setText("ス")
        self.ki.btn_se.setText("セ")
        self.ki.btn_so.setText("ソ")
        self.ki.btn_ta.setText("タ")
        self.ki.btn_chi.setText("チ")
        self.ki.btn_tsu.setText("ツ")
        self.ki.btn_te.setText("テ")
        self.ki.btn_to.setText("ト")
        self.ki.btn_na.setText("ナ")
        self.ki.btn_ni.setText("ニ")
        self.ki.btn_nu.setText("ヌ")
        self.ki.btn_ne.setText("ネ")
        self.ki.btn_no.setText("ノ")
        self.ki.btn_ha.setText("ハ")
        self.ki.btn_hi.setText("ヒ")
        self.ki.btn_fu.setText("フ")
        self.ki.btn_he.setText("ヘ")
        self.ki.btn_ho.setText("ホ")
        self.ki.btn_ma.setText("マ")
        self.ki.btn_mi.setText("ミ")
        self.ki.btn_mu.setText("ム")
        self.ki.btn_me.setText("メ")
        self.ki.btn_mo.setText("モ")
        self.ki.btn_ya.setText("ヤ")
        self.ki.btn_yu.setText("ユ")
        self.ki.btn_yo.setText("ヨ")
        self.ki.btn_wa.setText("ワ")
        self.ki.btn_n.setText("ン")
        self.ki.btn_ra.setText("ラ")
        self.ki.btn_ri.setText("リ")
        self.ki.btn_ru.setText("ル")
        self.ki.btn_re.setText("レ")
        self.ki.btn_ro.setText("ロ")

        self.ki.btn_kana.setText("あ")

    elif kana == "hiragana":
        self.ki.btn_a.setText("あ")
        self.ki.btn_i.setText("い")
        self.ki.btn_u.setText("う")
        self.ki.btn_e.setText("え")
        self.ki.btn_o.setText("お")
        self.ki.btn_ka.setText("か")
        self.ki.btn_ki.setText("き")
        self.ki.btn_ku.setText("く")
        self.ki.btn_ke.setText("け")
        self.ki.btn_ko.setText("こ")
        self.ki.btn_sa.setText("さ")
        self.ki.btn_shi.setText("し")
        self.ki.btn_su.setText("す")
        self.ki.btn_se.setText("せ")
        self.ki.btn_so.setText("そ")
        self.ki.btn_ta.setText("た")
        self.ki.btn_chi.setText("ち")
        self.ki.btn_tsu.setText("つ")
        self.ki.btn_te.setText("て")
        self.ki.btn_to.setText("と")
        self.ki.btn_na.setText("な")
        self.ki.btn_ni.setText("に")
        self.ki.btn_nu.setText("ぬ")
        self.ki.btn_ne.setText("ね")
        self.ki.btn_no.setText("の")
        self.ki.btn_ha.setText("は")
        self.ki.btn_hi.setText("ひ")
        self.ki.btn_fu.setText("ふ")
        self.ki.btn_he.setText("へ")
        self.ki.btn_ho.setText("ほ")
        self.ki.btn_ma.setText("ま")
        self.ki.btn_mi.setText("み")
        self.ki.btn_mu.setText("む")
        self.ki.btn_me.setText("め")
        self.ki.btn_mo.setText("も")
        self.ki.btn_ya.setText("や")
        self.ki.btn_yu.setText("ゆ")
        self.ki.btn_yo.setText("よ")
        self.ki.btn_wa.setText("わ")
        self.ki.btn_n.setText("ん")
        self.ki.btn_ra.setText("ら")
        self.ki.btn_ri.setText("り")
        self.ki.btn_ru.setText("る")
        self.ki.btn_re.setText("れ")
        self.ki.btn_ro.setText("ろ")

        self.ki.btn_kana.setText("ア")


def add_mark(letter: str) -> str:
    marked_letter = dictionary["letter_with_sound_mark"].get(letter)
    if marked_letter:
        return marked_letter
    else:
        return letter


def change_letter_size(letter: str) -> str:
    small_letter = dictionary["small_letter"].get(letter)
    if small_letter:
        return small_letter
    else:
        return letter
