import configparser

from PySide6.QtCore import Qt
from PySide6.QtGui import QCursor

dictionary = configparser.ConfigParser()
dictionary.read("./dictionaries/keyboard.dict", "utf-8")


def connect_keyboard_button(self):
    keyboard = self.main_keyboard.ki
    
    keyboard.btn_a.clicked.connect(lambda: self.keyboard_print(keyboard.btn_a.text()))
    keyboard.btn_i.clicked.connect(lambda: self.keyboard_print(keyboard.btn_i.text()))
    keyboard.btn_u.clicked.connect(lambda: self.keyboard_print(keyboard.btn_u.text()))
    keyboard.btn_e.clicked.connect(lambda: self.keyboard_print(keyboard.btn_e.text()))
    keyboard.btn_o.clicked.connect(lambda: self.keyboard_print(keyboard.btn_o.text()))
    keyboard.btn_ka.clicked.connect(lambda: self.keyboard_print(keyboard.btn_ka.text()))
    keyboard.btn_ki.clicked.connect(lambda: self.keyboard_print(keyboard.btn_ki.text()))
    keyboard.btn_ku.clicked.connect(lambda: self.keyboard_print(keyboard.btn_ku.text()))
    keyboard.btn_ke.clicked.connect(lambda: self.keyboard_print(keyboard.btn_ke.text()))
    keyboard.btn_ko.clicked.connect(lambda: self.keyboard_print(keyboard.btn_ko.text()))
    keyboard.btn_sa.clicked.connect(lambda: self.keyboard_print(keyboard.btn_sa.text()))
    keyboard.btn_shi.clicked.connect(lambda: self.keyboard_print(keyboard.btn_shi.text()))
    keyboard.btn_su.clicked.connect(lambda: self.keyboard_print(keyboard.btn_su.text()))
    keyboard.btn_se.clicked.connect(lambda: self.keyboard_print(keyboard.btn_se.text()))
    keyboard.btn_so.clicked.connect(lambda: self.keyboard_print(keyboard.btn_so.text()))
    keyboard.btn_ta.clicked.connect(lambda: self.keyboard_print(keyboard.btn_ta.text()))
    keyboard.btn_chi.clicked.connect(lambda: self.keyboard_print(keyboard.btn_chi.text()))
    keyboard.btn_tsu.clicked.connect(lambda: self.keyboard_print(keyboard.btn_tsu.text()))
    keyboard.btn_te.clicked.connect(lambda: self.keyboard_print(keyboard.btn_te.text()))
    keyboard.btn_to.clicked.connect(lambda: self.keyboard_print(keyboard.btn_to.text()))
    keyboard.btn_na.clicked.connect(lambda: self.keyboard_print(keyboard.btn_na.text()))
    keyboard.btn_ni.clicked.connect(lambda: self.keyboard_print(keyboard.btn_ni.text()))
    keyboard.btn_nu.clicked.connect(lambda: self.keyboard_print(keyboard.btn_nu.text()))
    keyboard.btn_ne.clicked.connect(lambda: self.keyboard_print(keyboard.btn_ne.text()))
    keyboard.btn_no.clicked.connect(lambda: self.keyboard_print(keyboard.btn_no.text()))
    keyboard.btn_ha.clicked.connect(lambda: self.keyboard_print(keyboard.btn_ha.text()))
    keyboard.btn_hi.clicked.connect(lambda: self.keyboard_print(keyboard.btn_hi.text()))
    keyboard.btn_fu.clicked.connect(lambda: self.keyboard_print(keyboard.btn_fu.text()))
    keyboard.btn_he.clicked.connect(lambda: self.keyboard_print(keyboard.btn_he.text()))
    keyboard.btn_ho.clicked.connect(lambda: self.keyboard_print(keyboard.btn_ho.text()))
    keyboard.btn_ma.clicked.connect(lambda: self.keyboard_print(keyboard.btn_ma.text()))
    keyboard.btn_mi.clicked.connect(lambda: self.keyboard_print(keyboard.btn_mi.text()))
    keyboard.btn_mu.clicked.connect(lambda: self.keyboard_print(keyboard.btn_mu.text()))
    keyboard.btn_me.clicked.connect(lambda: self.keyboard_print(keyboard.btn_me.text()))
    keyboard.btn_mo.clicked.connect(lambda: self.keyboard_print(keyboard.btn_mo.text()))
    keyboard.btn_ya.clicked.connect(lambda: self.keyboard_print(keyboard.btn_ya.text()))
    keyboard.btn_yu.clicked.connect(lambda: self.keyboard_print(keyboard.btn_yu.text()))
    keyboard.btn_yo.clicked.connect(lambda: self.keyboard_print(keyboard.btn_yo.text()))
    keyboard.btn_wa.clicked.connect(lambda: self.keyboard_print(keyboard.btn_wa.text()))
    keyboard.btn_n.clicked.connect(lambda: self.keyboard_print(keyboard.btn_n.text()))
    keyboard.btn_ra.clicked.connect(lambda: self.keyboard_print(keyboard.btn_ra.text()))
    keyboard.btn_ri.clicked.connect(lambda: self.keyboard_print(keyboard.btn_ri.text()))
    keyboard.btn_ru.clicked.connect(lambda: self.keyboard_print(keyboard.btn_ru.text()))
    keyboard.btn_re.clicked.connect(lambda: self.keyboard_print(keyboard.btn_re.text()))
    keyboard.btn_ro.clicked.connect(lambda: self.keyboard_print(keyboard.btn_ro.text()))
    keyboard.btn_dash.clicked.connect(lambda: self.keyboard_print(keyboard.btn_dash.text()))

    keyboard.btn_mark.clicked.connect(self.add_sound_mark)
    keyboard.btn_small.clicked.connect(self.change_letter_size)
    keyboard.btn_kana.clicked.connect(self.main_keyboard.change_kana)
    keyboard.btn_search.clicked.connect(self.start_search)
    keyboard.btn_backspace.clicked.connect(self.backspace)
    keyboard.btn_clear.clicked.connect(self.clear_search_input)


def set_keyboard_keymap(self, kana: str, keyboard: str):
    if kana == "katakana" and keyboard in ["main", "add_sound"]:
        self.btn_a.setText("ア")
        self.btn_i.setText("イ")
        self.btn_u.setText("ウ")
        self.btn_e.setText("エ")
        self.btn_o.setText("オ")
        self.btn_ka.setText("カ")
        self.btn_ki.setText("キ")
        self.btn_ku.setText("ク")
        self.btn_ke.setText("ケ")
        self.btn_ko.setText("コ")
        self.btn_sa.setText("サ")
        self.btn_shi.setText("シ")
        self.btn_su.setText("ス")
        self.btn_se.setText("セ")
        self.btn_so.setText("ソ")
        self.btn_ta.setText("タ")
        self.btn_chi.setText("チ")
        self.btn_tsu.setText("ツ")
        self.btn_te.setText("テ")
        self.btn_to.setText("ト")
        self.btn_na.setText("ナ")
        self.btn_ni.setText("ニ")
        self.btn_nu.setText("ヌ")
        self.btn_ne.setText("ネ")
        self.btn_no.setText("ノ")
        self.btn_ha.setText("ハ")
        self.btn_hi.setText("ヒ")
        self.btn_fu.setText("フ")
        self.btn_he.setText("ヘ")
        self.btn_ho.setText("ホ")
        self.btn_ma.setText("マ")
        self.btn_mi.setText("ミ")
        self.btn_mu.setText("ム")
        self.btn_me.setText("メ")
        self.btn_mo.setText("モ")
        self.btn_ya.setText("ヤ")
        self.btn_.setText("")
        self.btn_yu.setText("ユ")
        self.btn_yo.setText("ヨ")
        self.btn_wa.setText("ワ")
        self.btn_n.setText("ン")
        self.btn_ra.setText("ラ")
        self.btn_ri.setText("リ")
        self.btn_ru.setText("ル")
        self.btn_re.setText("レ")
        self.btn_ro.setText("ロ")

        self.btn_kana.setText("abc")

    elif kana == "hiragana" and keyboard in ["main", "add_sound"]:
        self.btn_a.setText("あ")
        self.btn_i.setText("い")
        self.btn_u.setText("う")
        self.btn_e.setText("え")
        self.btn_o.setText("お")
        self.btn_ka.setText("か")
        self.btn_ki.setText("き")
        self.btn_ku.setText("く")
        self.btn_ke.setText("け")
        self.btn_ko.setText("こ")
        self.btn_sa.setText("さ")
        self.btn_shi.setText("し")
        self.btn_su.setText("す")
        self.btn_se.setText("せ")
        self.btn_so.setText("そ")
        self.btn_ta.setText("た")
        self.btn_chi.setText("ち")
        self.btn_tsu.setText("つ")
        self.btn_te.setText("て")
        self.btn_to.setText("と")
        self.btn_na.setText("な")
        self.btn_ni.setText("に")
        self.btn_nu.setText("ぬ")
        self.btn_ne.setText("ね")
        self.btn_no.setText("の")
        self.btn_ha.setText("は")
        self.btn_hi.setText("ひ")
        self.btn_fu.setText("ふ")
        self.btn_he.setText("へ")
        self.btn_ho.setText("ほ")
        self.btn_ma.setText("ま")
        self.btn_mi.setText("み")
        self.btn_mu.setText("む")
        self.btn_me.setText("め")
        self.btn_mo.setText("も")
        self.btn_ya.setText("や")
        self.btn_.setText("")
        self.btn_yu.setText("ゆ")
        self.btn_yo.setText("よ")
        self.btn_wa.setText("わ")
        self.btn_n.setText("ん")
        self.btn_ra.setText("ら")
        self.btn_ri.setText("り")
        self.btn_ru.setText("る")
        self.btn_re.setText("れ")
        self.btn_ro.setText("ろ")

        self.btn_kana.setText("ア")

    elif kana == "english" and keyboard in ["add_sound"]:
        self.btn_ra.setText("a")
        self.btn_ya.setText("b")
        self.btn_ma.setText("c")
        self.btn_ha.setText("d")
        self.btn_na.setText("e")
        self.btn_ta.setText("f")
        self.btn_sa.setText("g")
        self.btn_ka.setText("h")
        self.btn_a.setText("i")

        self.btn_ri.setText("j")
        self.btn_.setText("k")
        self.btn_.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_mi.setText("l")
        self.btn_hi.setText("m")
        self.btn_ni.setText("n")
        self.btn_chi.setText("o")
        self.btn_shi.setText("p")
        self.btn_ki.setText("q")
        self.btn_i.setText("r")

        self.btn_ru.setText("s")
        self.btn_yu.setText("t")
        self.btn_mu.setText("u")
        self.btn_fu.setText("v")
        self.btn_na.setText("w")
        self.btn_tsu.setText("x")
        self.btn_su.setText("y")
        self.btn_ku.setText("z")

        # устанавливаем оставшимся кнопкам пустой текс
        self.btn_u.setText("")
        self.btn_re.setText("")
        self.btn_1.setText("")
        self.btn_me.setText("")
        self.btn_he.setText("")
        self.btn_ne.setText("")
        self.btn_te.setText("")
        self.btn_se.setText("")
        self.btn_ke.setText("")
        self.btn_e.setText("")
        self.btn_ro.setText("")
        self.btn_yo.setText("")
        self.btn_mo.setText("")
        self.btn_ho.setText("")
        self.btn_no.setText("")
        self.btn_to.setText("")
        self.btn_so.setText("")
        self.btn_ko.setText("")
        self.btn_o.setText("")
        self.btn_n.setText("")
        self.btn_wa.setText("")

        self.btn_kana.setText("あ")


def add_sound_keyboard_button_connect(self):
    self.ui.btn_a.clicked.connect(lambda: self.keyboard_print(self.ui.btn_a.text()))
    self.ui.btn_i.clicked.connect(lambda: self.keyboard_print(self.ui.btn_i.text()))
    self.ui.btn_u.clicked.connect(lambda: self.keyboard_print(self.ui.btn_u.text()))
    self.ui.btn_e.clicked.connect(lambda: self.keyboard_print(self.ui.btn_e.text()))
    self.ui.btn_o.clicked.connect(lambda: self.keyboard_print(self.ui.btn_o.text()))
    self.ui.btn_ka.clicked.connect(lambda: self.keyboard_print(self.ui.btn_ka.text()))
    self.ui.btn_ki.clicked.connect(lambda: self.keyboard_print(self.ui.btn_ki.text()))
    self.ui.btn_ku.clicked.connect(lambda: self.keyboard_print(self.ui.btn_ku.text()))
    self.ui.btn_ke.clicked.connect(lambda: self.keyboard_print(self.ui.btn_ke.text()))
    self.ui.btn_ko.clicked.connect(lambda: self.keyboard_print(self.ui.btn_ko.text()))
    self.ui.btn_sa.clicked.connect(lambda: self.keyboard_print(self.ui.btn_sa.text()))
    self.ui.btn_shi.clicked.connect(lambda: self.keyboard_print(self.ui.btn_shi.text()))
    self.ui.btn_su.clicked.connect(lambda: self.keyboard_print(self.ui.btn_su.text()))
    self.ui.btn_se.clicked.connect(lambda: self.keyboard_print(self.ui.btn_se.text()))
    self.ui.btn_so.clicked.connect(lambda: self.keyboard_print(self.ui.btn_so.text()))
    self.ui.btn_ta.clicked.connect(lambda: self.keyboard_print(self.ui.btn_ta.text()))
    self.ui.btn_chi.clicked.connect(lambda: self.keyboard_print(self.ui.btn_chi.text()))
    self.ui.btn_tsu.clicked.connect(lambda: self.keyboard_print(self.ui.btn_tsu.text()))
    self.ui.btn_te.clicked.connect(lambda: self.keyboard_print(self.ui.btn_te.text()))
    self.ui.btn_to.clicked.connect(lambda: self.keyboard_print(self.ui.btn_to.text()))
    self.ui.btn_na.clicked.connect(lambda: self.keyboard_print(self.ui.btn_na.text()))
    self.ui.btn_ni.clicked.connect(lambda: self.keyboard_print(self.ui.btn_ni.text()))
    self.ui.btn_nu.clicked.connect(lambda: self.keyboard_print(self.ui.btn_nu.text()))
    self.ui.btn_ne.clicked.connect(lambda: self.keyboard_print(self.ui.btn_ne.text()))
    self.ui.btn_no.clicked.connect(lambda: self.keyboard_print(self.ui.btn_no.text()))
    self.ui.btn_ha.clicked.connect(lambda: self.keyboard_print(self.ui.btn_ha.text()))
    self.ui.btn_hi.clicked.connect(lambda: self.keyboard_print(self.ui.btn_hi.text()))
    self.ui.btn_fu.clicked.connect(lambda: self.keyboard_print(self.ui.btn_fu.text()))
    self.ui.btn_he.clicked.connect(lambda: self.keyboard_print(self.ui.btn_he.text()))
    self.ui.btn_ho.clicked.connect(lambda: self.keyboard_print(self.ui.btn_ho.text()))
    self.ui.btn_ma.clicked.connect(lambda: self.keyboard_print(self.ui.btn_ma.text()))
    self.ui.btn_mi.clicked.connect(lambda: self.keyboard_print(self.ui.btn_mi.text()))
    self.ui.btn_mu.clicked.connect(lambda: self.keyboard_print(self.ui.btn_mu.text()))
    self.ui.btn_me.clicked.connect(lambda: self.keyboard_print(self.ui.btn_me.text()))
    self.ui.btn_mo.clicked.connect(lambda: self.keyboard_print(self.ui.btn_mo.text()))
    self.ui.btn_ya.clicked.connect(lambda: self.keyboard_print(self.ui.btn_ya.text()))
    self.ui.btn_.clicked.connect(lambda: self.keyboard_print(self.ui.btn_.text()))
    self.ui.btn_yu.clicked.connect(lambda: self.keyboard_print(self.ui.btn_yu.text()))
    self.ui.btn_yo.clicked.connect(lambda: self.keyboard_print(self.ui.btn_yo.text()))
    self.ui.btn_wa.clicked.connect(lambda: self.keyboard_print(self.ui.btn_wa.text()))
    self.ui.btn_n.clicked.connect(lambda: self.keyboard_print(self.ui.btn_n.text()))
    self.ui.btn_ra.clicked.connect(lambda: self.keyboard_print(self.ui.btn_ra.text()))
    self.ui.btn_ri.clicked.connect(lambda: self.keyboard_print(self.ui.btn_ri.text()))
    self.ui.btn_ru.clicked.connect(lambda: self.keyboard_print(self.ui.btn_ru.text()))
    self.ui.btn_re.clicked.connect(lambda: self.keyboard_print(self.ui.btn_re.text()))
    self.ui.btn_ro.clicked.connect(lambda: self.keyboard_print(self.ui.btn_ro.text()))
    self.ui.btn_dash.clicked.connect(lambda: self.keyboard_print(self.ui.btn_dash.text()))


def add_mark(letter: str) -> str:
    marked_letter = dictionary["letter_with_sound_mark"].get(letter)
    if marked_letter:
        return marked_letter
    else:
        return letter


def change_letter_size(letter: str) -> str:
    small_letter = dictionary["small_letter"].get(letter)
    if small_letter:
        return small_letter
    else:
        return letter
