from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QGridLayout, QPushButton, QSizePolicy,
    QSpacerItem, QWidget)

class Ui_main_keyboard(object):
    def setupUi(self, main_keyboard):
        if not main_keyboard.objectName():
            main_keyboard.setObjectName(u"main_keyboard")
        main_keyboard.resize(212, 490)
        main_keyboard.setStyleSheet(u"background-color: rgba(255, 255, 255, 150);\n"
"")
        main_keyboard.setLocale(QLocale(QLocale.Russian, QLocale.Ukraine))
        self.gridLayout = QGridLayout(main_keyboard)
        self.gridLayout.setSpacing(2)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(2, 2, 2, 2)
        self.btn_ni = QPushButton(main_keyboard)
        self.btn_ni.setObjectName(u"btn_ni")
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.btn_ni.sizePolicy().hasHeightForWidth())
        self.btn_ni.setSizePolicy(sizePolicy)
        self.btn_ni.setMinimumSize(QSize(25, 25))
        font = QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.btn_ni.setFont(font)
        self.btn_ni.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_ni.setTabletTracking(False)

        self.gridLayout.addWidget(self.btn_ni, 1, 0, 1, 1)

        self.btn_ra = QPushButton(main_keyboard)
        self.btn_ra.setObjectName(u"btn_ra")
        sizePolicy.setHeightForWidth(self.btn_ra.sizePolicy().hasHeightForWidth())
        self.btn_ra.setSizePolicy(sizePolicy)
        self.btn_ra.setMinimumSize(QSize(25, 25))
        self.btn_ra.setFont(font)
        self.btn_ra.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_ra.setTabletTracking(False)

        self.gridLayout.addWidget(self.btn_ra, 6, 1, 1, 1)

        self.btn_ho = QPushButton(main_keyboard)
        self.btn_ho.setObjectName(u"btn_ho")
        sizePolicy.setHeightForWidth(self.btn_ho.sizePolicy().hasHeightForWidth())
        self.btn_ho.setSizePolicy(sizePolicy)
        self.btn_ho.setMinimumSize(QSize(25, 25))
        self.btn_ho.setFont(font)
        self.btn_ho.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_ho.setTabletTracking(False)

        self.gridLayout.addWidget(self.btn_ho, 10, 4, 1, 1)

        self.btn_small = QPushButton(main_keyboard)
        self.btn_small.setObjectName(u"btn_small")
        sizePolicy.setHeightForWidth(self.btn_small.sizePolicy().hasHeightForWidth())
        self.btn_small.setSizePolicy(sizePolicy)
        self.btn_small.setMinimumSize(QSize(25, 25))
        font1 = QFont()
        font1.setPointSize(14)
        font1.setBold(False)
        self.btn_small.setFont(font1)
        self.btn_small.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_small.setTabletTracking(False)

        self.gridLayout.addWidget(self.btn_small, 16, 1, 1, 1)

        self.btn_hi = QPushButton(main_keyboard)
        self.btn_hi.setObjectName(u"btn_hi")
        sizePolicy.setHeightForWidth(self.btn_hi.sizePolicy().hasHeightForWidth())
        self.btn_hi.setSizePolicy(sizePolicy)
        self.btn_hi.setMinimumSize(QSize(25, 25))
        self.btn_hi.setFont(font)
        self.btn_hi.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_hi.setTabletTracking(False)

        self.gridLayout.addWidget(self.btn_hi, 7, 4, 1, 1)

        self.btn_ne = QPushButton(main_keyboard)
        self.btn_ne.setObjectName(u"btn_ne")
        sizePolicy.setHeightForWidth(self.btn_ne.sizePolicy().hasHeightForWidth())
        self.btn_ne.setSizePolicy(sizePolicy)
        self.btn_ne.setMinimumSize(QSize(25, 25))
        self.btn_ne.setFont(font)
        self.btn_ne.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_ne.setTabletTracking(False)

        self.gridLayout.addWidget(self.btn_ne, 3, 0, 1, 1)

        self.btn_2 = QPushButton(main_keyboard)
        self.btn_2.setObjectName(u"btn_2")
        sizePolicy.setHeightForWidth(self.btn_2.sizePolicy().hasHeightForWidth())
        self.btn_2.setSizePolicy(sizePolicy)
        self.btn_2.setMinimumSize(QSize(25, 25))
        self.btn_2.setFont(font)
        self.btn_2.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_2.setTabletTracking(False)

        self.gridLayout.addWidget(self.btn_2, 9, 2, 1, 1)

        self.btn_ko = QPushButton(main_keyboard)
        self.btn_ko.setObjectName(u"btn_ko")
        sizePolicy.setHeightForWidth(self.btn_ko.sizePolicy().hasHeightForWidth())
        self.btn_ko.setSizePolicy(sizePolicy)
        self.btn_ko.setMinimumSize(QSize(25, 25))
        self.btn_ko.setFont(font)
        self.btn_ko.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_ko.setTabletTracking(False)

        self.gridLayout.addWidget(self.btn_ko, 4, 3, 1, 1)

        self.btn_o = QPushButton(main_keyboard)
        self.btn_o.setObjectName(u"btn_o")
        sizePolicy.setHeightForWidth(self.btn_o.sizePolicy().hasHeightForWidth())
        self.btn_o.setSizePolicy(sizePolicy)
        self.btn_o.setMinimumSize(QSize(25, 25))
        self.btn_o.setFont(font)
        self.btn_o.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_o.setTabletTracking(False)

        self.gridLayout.addWidget(self.btn_o, 4, 4, 1, 1)

        self.btn_wo = QPushButton(main_keyboard)
        self.btn_wo.setObjectName(u"btn_wo")
        sizePolicy.setHeightForWidth(self.btn_wo.sizePolicy().hasHeightForWidth())
        self.btn_wo.setSizePolicy(sizePolicy)
        self.btn_wo.setMinimumSize(QSize(25, 25))
        self.btn_wo.setFont(font)
        self.btn_wo.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_wo.setTabletTracking(False)

        self.gridLayout.addWidget(self.btn_wo, 7, 0, 1, 1)

        self.btn_re = QPushButton(main_keyboard)
        self.btn_re.setObjectName(u"btn_re")
        sizePolicy.setHeightForWidth(self.btn_re.sizePolicy().hasHeightForWidth())
        self.btn_re.setSizePolicy(sizePolicy)
        self.btn_re.setMinimumSize(QSize(25, 25))
        self.btn_re.setFont(font)
        self.btn_re.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_re.setTabletTracking(False)

        self.gridLayout.addWidget(self.btn_re, 9, 1, 1, 1)

        self.btn_dash = QPushButton(main_keyboard)
        self.btn_dash.setObjectName(u"btn_dash")
        sizePolicy.setHeightForWidth(self.btn_dash.sizePolicy().hasHeightForWidth())
        self.btn_dash.setSizePolicy(sizePolicy)
        self.btn_dash.setMinimumSize(QSize(25, 25))
        font2 = QFont()
        font2.setPointSize(18)
        font2.setBold(True)
        font2.setItalic(False)
        self.btn_dash.setFont(font2)
        self.btn_dash.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_dash.setTabletTracking(False)

        self.gridLayout.addWidget(self.btn_dash, 9, 0, 1, 1)

        self.btn_backspace = QPushButton(main_keyboard)
        self.btn_backspace.setObjectName(u"btn_backspace")
        sizePolicy.setHeightForWidth(self.btn_backspace.sizePolicy().hasHeightForWidth())
        self.btn_backspace.setSizePolicy(sizePolicy)
        self.btn_backspace.setMinimumSize(QSize(25, 25))
        font3 = QFont()
        font3.setPointSize(20)
        font3.setBold(True)
        self.btn_backspace.setFont(font3)
        self.btn_backspace.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_backspace.setTabletTracking(False)

        self.gridLayout.addWidget(self.btn_backspace, 10, 0, 1, 1)

        self.btn_ka = QPushButton(main_keyboard)
        self.btn_ka.setObjectName(u"btn_ka")
        sizePolicy.setHeightForWidth(self.btn_ka.sizePolicy().hasHeightForWidth())
        self.btn_ka.setSizePolicy(sizePolicy)
        self.btn_ka.setMinimumSize(QSize(25, 25))
        self.btn_ka.setFont(font)
        self.btn_ka.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_ka.setTabletTracking(False)

        self.gridLayout.addWidget(self.btn_ka, 0, 3, 1, 1)

        self.btn_ya = QPushButton(main_keyboard)
        self.btn_ya.setObjectName(u"btn_ya")
        sizePolicy.setHeightForWidth(self.btn_ya.sizePolicy().hasHeightForWidth())
        self.btn_ya.setSizePolicy(sizePolicy)
        self.btn_ya.setMinimumSize(QSize(25, 25))
        self.btn_ya.setFont(font)
        self.btn_ya.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_ya.setTabletTracking(False)

        self.gridLayout.addWidget(self.btn_ya, 6, 2, 1, 1)

        self.btn_1 = QPushButton(main_keyboard)
        self.btn_1.setObjectName(u"btn_1")
        sizePolicy.setHeightForWidth(self.btn_1.sizePolicy().hasHeightForWidth())
        self.btn_1.setSizePolicy(sizePolicy)
        self.btn_1.setMinimumSize(QSize(25, 25))
        self.btn_1.setFont(font)
        self.btn_1.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_1.setTabletTracking(False)

        self.gridLayout.addWidget(self.btn_1, 7, 2, 1, 1)

        self.btn_no = QPushButton(main_keyboard)
        self.btn_no.setObjectName(u"btn_no")
        sizePolicy.setHeightForWidth(self.btn_no.sizePolicy().hasHeightForWidth())
        self.btn_no.setSizePolicy(sizePolicy)
        self.btn_no.setMinimumSize(QSize(25, 25))
        self.btn_no.setFont(font)
        self.btn_no.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_no.setTabletTracking(False)

        self.gridLayout.addWidget(self.btn_no, 4, 0, 1, 1)

        self.btn_to = QPushButton(main_keyboard)
        self.btn_to.setObjectName(u"btn_to")
        sizePolicy.setHeightForWidth(self.btn_to.sizePolicy().hasHeightForWidth())
        self.btn_to.setSizePolicy(sizePolicy)
        self.btn_to.setMinimumSize(QSize(25, 25))
        self.btn_to.setFont(font)
        self.btn_to.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_to.setTabletTracking(False)

        self.gridLayout.addWidget(self.btn_to, 4, 1, 1, 1)

        self.btn_te = QPushButton(main_keyboard)
        self.btn_te.setObjectName(u"btn_te")
        sizePolicy.setHeightForWidth(self.btn_te.sizePolicy().hasHeightForWidth())
        self.btn_te.setSizePolicy(sizePolicy)
        self.btn_te.setMinimumSize(QSize(25, 25))
        self.btn_te.setFont(font)
        self.btn_te.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_te.setTabletTracking(False)

        self.gridLayout.addWidget(self.btn_te, 3, 1, 1, 1)

        self.btn_su = QPushButton(main_keyboard)
        self.btn_su.setObjectName(u"btn_su")
        sizePolicy.setHeightForWidth(self.btn_su.sizePolicy().hasHeightForWidth())
        self.btn_su.setSizePolicy(sizePolicy)
        self.btn_su.setMinimumSize(QSize(25, 25))
        self.btn_su.setFont(font)
        self.btn_su.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_su.setTabletTracking(False)

        self.gridLayout.addWidget(self.btn_su, 2, 2, 1, 1)

        self.btn_yu = QPushButton(main_keyboard)
        self.btn_yu.setObjectName(u"btn_yu")
        sizePolicy.setHeightForWidth(self.btn_yu.sizePolicy().hasHeightForWidth())
        self.btn_yu.setSizePolicy(sizePolicy)
        self.btn_yu.setMinimumSize(QSize(25, 25))
        self.btn_yu.setFont(font)
        self.btn_yu.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_yu.setTabletTracking(False)

        self.gridLayout.addWidget(self.btn_yu, 8, 2, 1, 1)

        self.btn_mark = QPushButton(main_keyboard)
        self.btn_mark.setObjectName(u"btn_mark")
        sizePolicy.setHeightForWidth(self.btn_mark.sizePolicy().hasHeightForWidth())
        self.btn_mark.setSizePolicy(sizePolicy)
        self.btn_mark.setMinimumSize(QSize(25, 25))
        font4 = QFont()
        font4.setPointSize(18)
        font4.setBold(False)
        self.btn_mark.setFont(font4)
        self.btn_mark.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_mark.setTabletTracking(False)

        self.gridLayout.addWidget(self.btn_mark, 16, 2, 1, 1)

        self.verticalSpacer = QSpacerItem(5, 5, QSizePolicy.Minimum, QSizePolicy.Fixed)

        self.gridLayout.addItem(self.verticalSpacer, 5, 2, 1, 1)

        self.btn_so = QPushButton(main_keyboard)
        self.btn_so.setObjectName(u"btn_so")
        sizePolicy.setHeightForWidth(self.btn_so.sizePolicy().hasHeightForWidth())
        self.btn_so.setSizePolicy(sizePolicy)
        self.btn_so.setMinimumSize(QSize(25, 25))
        self.btn_so.setFont(font)
        self.btn_so.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_so.setTabletTracking(False)

        self.gridLayout.addWidget(self.btn_so, 4, 2, 1, 1)

        self.btn_mo = QPushButton(main_keyboard)
        self.btn_mo.setObjectName(u"btn_mo")
        sizePolicy.setHeightForWidth(self.btn_mo.sizePolicy().hasHeightForWidth())
        self.btn_mo.setSizePolicy(sizePolicy)
        self.btn_mo.setMinimumSize(QSize(25, 25))
        self.btn_mo.setFont(font)
        self.btn_mo.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_mo.setTabletTracking(False)

        self.gridLayout.addWidget(self.btn_mo, 10, 3, 1, 1)

        self.btn_ri = QPushButton(main_keyboard)
        self.btn_ri.setObjectName(u"btn_ri")
        sizePolicy.setHeightForWidth(self.btn_ri.sizePolicy().hasHeightForWidth())
        self.btn_ri.setSizePolicy(sizePolicy)
        self.btn_ri.setMinimumSize(QSize(25, 25))
        self.btn_ri.setFont(font)
        self.btn_ri.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_ri.setTabletTracking(False)

        self.gridLayout.addWidget(self.btn_ri, 7, 1, 1, 1)

        self.btn_he = QPushButton(main_keyboard)
        self.btn_he.setObjectName(u"btn_he")
        sizePolicy.setHeightForWidth(self.btn_he.sizePolicy().hasHeightForWidth())
        self.btn_he.setSizePolicy(sizePolicy)
        self.btn_he.setMinimumSize(QSize(25, 25))
        self.btn_he.setFont(font)
        self.btn_he.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_he.setTabletTracking(False)

        self.gridLayout.addWidget(self.btn_he, 9, 4, 1, 1)

        self.btn_i = QPushButton(main_keyboard)
        self.btn_i.setObjectName(u"btn_i")
        sizePolicy.setHeightForWidth(self.btn_i.sizePolicy().hasHeightForWidth())
        self.btn_i.setSizePolicy(sizePolicy)
        self.btn_i.setMinimumSize(QSize(25, 25))
        self.btn_i.setFont(font)
        self.btn_i.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_i.setTabletTracking(False)

        self.gridLayout.addWidget(self.btn_i, 1, 4, 1, 1)

        self.btn_ma = QPushButton(main_keyboard)
        self.btn_ma.setObjectName(u"btn_ma")
        sizePolicy.setHeightForWidth(self.btn_ma.sizePolicy().hasHeightForWidth())
        self.btn_ma.setSizePolicy(sizePolicy)
        self.btn_ma.setMinimumSize(QSize(25, 25))
        self.btn_ma.setFont(font)
        self.btn_ma.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_ma.setTabletTracking(False)

        self.gridLayout.addWidget(self.btn_ma, 6, 3, 1, 1)

        self.btn_u = QPushButton(main_keyboard)
        self.btn_u.setObjectName(u"btn_u")
        sizePolicy.setHeightForWidth(self.btn_u.sizePolicy().hasHeightForWidth())
        self.btn_u.setSizePolicy(sizePolicy)
        self.btn_u.setMinimumSize(QSize(25, 25))
        self.btn_u.setFont(font)
        self.btn_u.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_u.setTabletTracking(False)

        self.gridLayout.addWidget(self.btn_u, 2, 4, 1, 1)

        self.btn_yo = QPushButton(main_keyboard)
        self.btn_yo.setObjectName(u"btn_yo")
        sizePolicy.setHeightForWidth(self.btn_yo.sizePolicy().hasHeightForWidth())
        self.btn_yo.setSizePolicy(sizePolicy)
        self.btn_yo.setMinimumSize(QSize(25, 25))
        self.btn_yo.setFont(font)
        self.btn_yo.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_yo.setTabletTracking(False)

        self.gridLayout.addWidget(self.btn_yo, 10, 2, 1, 1)

        self.btn_ha = QPushButton(main_keyboard)
        self.btn_ha.setObjectName(u"btn_ha")
        sizePolicy.setHeightForWidth(self.btn_ha.sizePolicy().hasHeightForWidth())
        self.btn_ha.setSizePolicy(sizePolicy)
        self.btn_ha.setMinimumSize(QSize(25, 25))
        self.btn_ha.setFont(font)
        self.btn_ha.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_ha.setTabletTracking(False)

        self.gridLayout.addWidget(self.btn_ha, 6, 4, 1, 1)

        self.btn_ki = QPushButton(main_keyboard)
        self.btn_ki.setObjectName(u"btn_ki")
        sizePolicy.setHeightForWidth(self.btn_ki.sizePolicy().hasHeightForWidth())
        self.btn_ki.setSizePolicy(sizePolicy)
        self.btn_ki.setMinimumSize(QSize(25, 25))
        self.btn_ki.setFont(font)
        self.btn_ki.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_ki.setTabletTracking(False)

        self.gridLayout.addWidget(self.btn_ki, 1, 3, 1, 1)

        self.btn_ta = QPushButton(main_keyboard)
        self.btn_ta.setObjectName(u"btn_ta")
        sizePolicy.setHeightForWidth(self.btn_ta.sizePolicy().hasHeightForWidth())
        self.btn_ta.setSizePolicy(sizePolicy)
        self.btn_ta.setMinimumSize(QSize(25, 25))
        self.btn_ta.setFont(font)
        self.btn_ta.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_ta.setTabletTracking(False)

        self.gridLayout.addWidget(self.btn_ta, 0, 1, 1, 1)

        self.btn_chi = QPushButton(main_keyboard)
        self.btn_chi.setObjectName(u"btn_chi")
        sizePolicy.setHeightForWidth(self.btn_chi.sizePolicy().hasHeightForWidth())
        self.btn_chi.setSizePolicy(sizePolicy)
        self.btn_chi.setMinimumSize(QSize(25, 25))
        self.btn_chi.setFont(font)
        self.btn_chi.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_chi.setTabletTracking(False)

        self.gridLayout.addWidget(self.btn_chi, 1, 1, 1, 1)

        self.btn_search = QPushButton(main_keyboard)
        self.btn_search.setObjectName(u"btn_search")
        sizePolicy.setHeightForWidth(self.btn_search.sizePolicy().hasHeightForWidth())
        self.btn_search.setSizePolicy(sizePolicy)
        self.btn_search.setMinimumSize(QSize(25, 25))
        font5 = QFont()
        font5.setPointSize(18)
        font5.setBold(True)
        self.btn_search.setFont(font5)
        self.btn_search.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_search.setTabletTracking(False)

        self.gridLayout.addWidget(self.btn_search, 16, 4, 1, 1)

        self.btn_ro = QPushButton(main_keyboard)
        self.btn_ro.setObjectName(u"btn_ro")
        sizePolicy.setHeightForWidth(self.btn_ro.sizePolicy().hasHeightForWidth())
        self.btn_ro.setSizePolicy(sizePolicy)
        self.btn_ro.setMinimumSize(QSize(25, 25))
        self.btn_ro.setFont(font)
        self.btn_ro.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_ro.setTabletTracking(False)

        self.gridLayout.addWidget(self.btn_ro, 10, 1, 1, 1)

        self.btn_ke = QPushButton(main_keyboard)
        self.btn_ke.setObjectName(u"btn_ke")
        sizePolicy.setHeightForWidth(self.btn_ke.sizePolicy().hasHeightForWidth())
        self.btn_ke.setSizePolicy(sizePolicy)
        self.btn_ke.setMinimumSize(QSize(25, 25))
        self.btn_ke.setFont(font)
        self.btn_ke.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_ke.setTabletTracking(False)

        self.gridLayout.addWidget(self.btn_ke, 3, 3, 1, 1)

        self.btn_a = QPushButton(main_keyboard)
        self.btn_a.setObjectName(u"btn_a")
        sizePolicy.setHeightForWidth(self.btn_a.sizePolicy().hasHeightForWidth())
        self.btn_a.setSizePolicy(sizePolicy)
        self.btn_a.setMinimumSize(QSize(25, 25))
        self.btn_a.setFont(font)
        self.btn_a.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_a.setTabletTracking(False)

        self.gridLayout.addWidget(self.btn_a, 0, 4, 1, 1)

        self.verticalSpacer_2 = QSpacerItem(5, 5, QSizePolicy.Minimum, QSizePolicy.Fixed)

        self.gridLayout.addItem(self.verticalSpacer_2, 11, 2, 1, 1)

        self.btn_se = QPushButton(main_keyboard)
        self.btn_se.setObjectName(u"btn_se")
        sizePolicy.setHeightForWidth(self.btn_se.sizePolicy().hasHeightForWidth())
        self.btn_se.setSizePolicy(sizePolicy)
        self.btn_se.setMinimumSize(QSize(25, 25))
        self.btn_se.setFont(font)
        self.btn_se.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_se.setTabletTracking(False)

        self.gridLayout.addWidget(self.btn_se, 3, 2, 1, 1)

        self.btn_ru = QPushButton(main_keyboard)
        self.btn_ru.setObjectName(u"btn_ru")
        sizePolicy.setHeightForWidth(self.btn_ru.sizePolicy().hasHeightForWidth())
        self.btn_ru.setSizePolicy(sizePolicy)
        self.btn_ru.setMinimumSize(QSize(25, 25))
        self.btn_ru.setFont(font)
        self.btn_ru.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_ru.setTabletTracking(False)

        self.gridLayout.addWidget(self.btn_ru, 8, 1, 1, 1)

        self.btn_mu = QPushButton(main_keyboard)
        self.btn_mu.setObjectName(u"btn_mu")
        sizePolicy.setHeightForWidth(self.btn_mu.sizePolicy().hasHeightForWidth())
        self.btn_mu.setSizePolicy(sizePolicy)
        self.btn_mu.setMinimumSize(QSize(25, 25))
        self.btn_mu.setFont(font)
        self.btn_mu.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_mu.setTabletTracking(False)

        self.gridLayout.addWidget(self.btn_mu, 8, 3, 1, 1)

        self.btn_kana = QPushButton(main_keyboard)
        self.btn_kana.setObjectName(u"btn_kana")
        sizePolicy.setHeightForWidth(self.btn_kana.sizePolicy().hasHeightForWidth())
        self.btn_kana.setSizePolicy(sizePolicy)
        self.btn_kana.setMinimumSize(QSize(25, 25))
        self.btn_kana.setFont(font1)
        self.btn_kana.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_kana.setTabletTracking(False)

        self.gridLayout.addWidget(self.btn_kana, 16, 0, 1, 1)

        self.btn_mi = QPushButton(main_keyboard)
        self.btn_mi.setObjectName(u"btn_mi")
        sizePolicy.setHeightForWidth(self.btn_mi.sizePolicy().hasHeightForWidth())
        self.btn_mi.setSizePolicy(sizePolicy)
        self.btn_mi.setMinimumSize(QSize(25, 25))
        self.btn_mi.setFont(font)
        self.btn_mi.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_mi.setTabletTracking(False)

        self.gridLayout.addWidget(self.btn_mi, 7, 3, 1, 1)

        self.btn_n = QPushButton(main_keyboard)
        self.btn_n.setObjectName(u"btn_n")
        sizePolicy.setHeightForWidth(self.btn_n.sizePolicy().hasHeightForWidth())
        self.btn_n.setSizePolicy(sizePolicy)
        self.btn_n.setMinimumSize(QSize(25, 25))
        self.btn_n.setFont(font)
        self.btn_n.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_n.setTabletTracking(False)

        self.gridLayout.addWidget(self.btn_n, 8, 0, 1, 1)

        self.btn_sa = QPushButton(main_keyboard)
        self.btn_sa.setObjectName(u"btn_sa")
        sizePolicy.setHeightForWidth(self.btn_sa.sizePolicy().hasHeightForWidth())
        self.btn_sa.setSizePolicy(sizePolicy)
        self.btn_sa.setMinimumSize(QSize(25, 25))
        self.btn_sa.setFont(font)
        self.btn_sa.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_sa.setTabletTracking(False)

        self.gridLayout.addWidget(self.btn_sa, 0, 2, 1, 1)

        self.btn_shi = QPushButton(main_keyboard)
        self.btn_shi.setObjectName(u"btn_shi")
        sizePolicy.setHeightForWidth(self.btn_shi.sizePolicy().hasHeightForWidth())
        self.btn_shi.setSizePolicy(sizePolicy)
        self.btn_shi.setMinimumSize(QSize(25, 25))
        self.btn_shi.setFont(font)
        self.btn_shi.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_shi.setTabletTracking(False)

        self.gridLayout.addWidget(self.btn_shi, 1, 2, 1, 1)

        self.btn_me = QPushButton(main_keyboard)
        self.btn_me.setObjectName(u"btn_me")
        sizePolicy.setHeightForWidth(self.btn_me.sizePolicy().hasHeightForWidth())
        self.btn_me.setSizePolicy(sizePolicy)
        self.btn_me.setMinimumSize(QSize(25, 25))
        self.btn_me.setFont(font)
        self.btn_me.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_me.setTabletTracking(False)

        self.gridLayout.addWidget(self.btn_me, 9, 3, 1, 1)

        self.btn_e = QPushButton(main_keyboard)
        self.btn_e.setObjectName(u"btn_e")
        sizePolicy.setHeightForWidth(self.btn_e.sizePolicy().hasHeightForWidth())
        self.btn_e.setSizePolicy(sizePolicy)
        self.btn_e.setMinimumSize(QSize(25, 25))
        self.btn_e.setFont(font)
        self.btn_e.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_e.setTabletTracking(False)

        self.gridLayout.addWidget(self.btn_e, 3, 4, 1, 1)

        self.btn_tsu = QPushButton(main_keyboard)
        self.btn_tsu.setObjectName(u"btn_tsu")
        sizePolicy.setHeightForWidth(self.btn_tsu.sizePolicy().hasHeightForWidth())
        self.btn_tsu.setSizePolicy(sizePolicy)
        self.btn_tsu.setMinimumSize(QSize(25, 25))
        self.btn_tsu.setFont(font)
        self.btn_tsu.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_tsu.setTabletTracking(False)

        self.gridLayout.addWidget(self.btn_tsu, 2, 1, 1, 1)

        self.btn_ku = QPushButton(main_keyboard)
        self.btn_ku.setObjectName(u"btn_ku")
        sizePolicy.setHeightForWidth(self.btn_ku.sizePolicy().hasHeightForWidth())
        self.btn_ku.setSizePolicy(sizePolicy)
        self.btn_ku.setMinimumSize(QSize(25, 25))
        self.btn_ku.setFont(font)
        self.btn_ku.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_ku.setTabletTracking(False)

        self.gridLayout.addWidget(self.btn_ku, 2, 3, 1, 1)

        self.btn_clear = QPushButton(main_keyboard)
        self.btn_clear.setObjectName(u"btn_clear")
        sizePolicy.setHeightForWidth(self.btn_clear.sizePolicy().hasHeightForWidth())
        self.btn_clear.setSizePolicy(sizePolicy)
        self.btn_clear.setMinimumSize(QSize(25, 25))
        self.btn_clear.setFont(font5)
        self.btn_clear.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_clear.setTabletTracking(False)

        self.gridLayout.addWidget(self.btn_clear, 16, 3, 1, 1)

        self.btn_wa = QPushButton(main_keyboard)
        self.btn_wa.setObjectName(u"btn_wa")
        sizePolicy.setHeightForWidth(self.btn_wa.sizePolicy().hasHeightForWidth())
        self.btn_wa.setSizePolicy(sizePolicy)
        self.btn_wa.setMinimumSize(QSize(25, 25))
        self.btn_wa.setFont(font)
        self.btn_wa.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_wa.setTabletTracking(False)

        self.gridLayout.addWidget(self.btn_wa, 6, 0, 1, 1)

        self.btn_nu = QPushButton(main_keyboard)
        self.btn_nu.setObjectName(u"btn_nu")
        sizePolicy.setHeightForWidth(self.btn_nu.sizePolicy().hasHeightForWidth())
        self.btn_nu.setSizePolicy(sizePolicy)
        self.btn_nu.setMinimumSize(QSize(25, 25))
        self.btn_nu.setFont(font)
        self.btn_nu.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_nu.setTabletTracking(False)

        self.gridLayout.addWidget(self.btn_nu, 2, 0, 1, 1)

        self.btn_fu = QPushButton(main_keyboard)
        self.btn_fu.setObjectName(u"btn_fu")
        sizePolicy.setHeightForWidth(self.btn_fu.sizePolicy().hasHeightForWidth())
        self.btn_fu.setSizePolicy(sizePolicy)
        self.btn_fu.setMinimumSize(QSize(25, 25))
        self.btn_fu.setFont(font)
        self.btn_fu.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_fu.setTabletTracking(False)

        self.gridLayout.addWidget(self.btn_fu, 8, 4, 1, 1)

        self.btn_na = QPushButton(main_keyboard)
        self.btn_na.setObjectName(u"btn_na")
        sizePolicy.setHeightForWidth(self.btn_na.sizePolicy().hasHeightForWidth())
        self.btn_na.setSizePolicy(sizePolicy)
        self.btn_na.setMinimumSize(QSize(25, 25))
        self.btn_na.setFont(font)
        self.btn_na.setCursor(QCursor(Qt.PointingHandCursor))
        self.btn_na.setTabletTracking(False)

        self.gridLayout.addWidget(self.btn_na, 0, 0, 1, 1)


        self.retranslateUi(main_keyboard)

        QMetaObject.connectSlotsByName(main_keyboard)
    # setupUi

    def retranslateUi(self, main_keyboard):
        main_keyboard.setWindowTitle(QCoreApplication.translate("main_keyboard", u"Form", None))
        self.btn_ni.setText(QCoreApplication.translate("main_keyboard", u"\u306b", None))
        self.btn_ra.setText(QCoreApplication.translate("main_keyboard", u"\u3089", None))
        self.btn_ho.setText(QCoreApplication.translate("main_keyboard", u"\u307b", None))
        self.btn_small.setText(QCoreApplication.translate("main_keyboard", u" \u3042\u3041", None))
        self.btn_hi.setText(QCoreApplication.translate("main_keyboard", u"\u3072", None))
        self.btn_ne.setText(QCoreApplication.translate("main_keyboard", u"\u306d", None))
        self.btn_2.setText("")
        self.btn_ko.setText(QCoreApplication.translate("main_keyboard", u"\u3053", None))
        self.btn_o.setText(QCoreApplication.translate("main_keyboard", u"\u304a", None))
        self.btn_wo.setText(QCoreApplication.translate("main_keyboard", u"\u3092", None))
        self.btn_re.setText(QCoreApplication.translate("main_keyboard", u"\u308c", None))
        self.btn_dash.setText(QCoreApplication.translate("main_keyboard", u"\u30fc", None))
        self.btn_backspace.setText(QCoreApplication.translate("main_keyboard", u"\u2190", None))
        self.btn_ka.setText(QCoreApplication.translate("main_keyboard", u"\u304b", None))
        self.btn_ya.setText(QCoreApplication.translate("main_keyboard", u"\u3084", None))
        self.btn_1.setText("")
        self.btn_no.setText(QCoreApplication.translate("main_keyboard", u"\u306e", None))
        self.btn_to.setText(QCoreApplication.translate("main_keyboard", u"\u3068", None))
        self.btn_te.setText(QCoreApplication.translate("main_keyboard", u"\u3066", None))
        self.btn_su.setText(QCoreApplication.translate("main_keyboard", u"\u3059", None))
        self.btn_yu.setText(QCoreApplication.translate("main_keyboard", u"\u3086", None))
        self.btn_mark.setText(QCoreApplication.translate("main_keyboard", u" \u309c\u309b ", None))
        self.btn_so.setText(QCoreApplication.translate("main_keyboard", u"\u305d", None))
        self.btn_mo.setText(QCoreApplication.translate("main_keyboard", u"\u3082", None))
        self.btn_ri.setText(QCoreApplication.translate("main_keyboard", u"\u308a", None))
        self.btn_he.setText(QCoreApplication.translate("main_keyboard", u"\u3078", None))
        self.btn_i.setText(QCoreApplication.translate("main_keyboard", u"\u3044", None))
        self.btn_ma.setText(QCoreApplication.translate("main_keyboard", u"\u307e", None))
        self.btn_u.setText(QCoreApplication.translate("main_keyboard", u"\u3046", None))
        self.btn_yo.setText(QCoreApplication.translate("main_keyboard", u"\u3088", None))
        self.btn_ha.setText(QCoreApplication.translate("main_keyboard", u"\u306f", None))
        self.btn_ki.setText(QCoreApplication.translate("main_keyboard", u"\u304d", None))
        self.btn_ta.setText(QCoreApplication.translate("main_keyboard", u"\u305f", None))
        self.btn_chi.setText(QCoreApplication.translate("main_keyboard", u"\u3061", None))
        self.btn_search.setText(QCoreApplication.translate("main_keyboard", u"\u21b5", None))
        self.btn_ro.setText(QCoreApplication.translate("main_keyboard", u"\u308d", None))
        self.btn_ke.setText(QCoreApplication.translate("main_keyboard", u"\u3051", None))
        self.btn_a.setText(QCoreApplication.translate("main_keyboard", u"\u3042", None))
        self.btn_se.setText(QCoreApplication.translate("main_keyboard", u"\u305b", None))
        self.btn_ru.setText(QCoreApplication.translate("main_keyboard", u"\u308b", None))
        self.btn_mu.setText(QCoreApplication.translate("main_keyboard", u"\u3080", None))
        self.btn_kana.setText(QCoreApplication.translate("main_keyboard", u"\u30a2", None))
        self.btn_mi.setText(QCoreApplication.translate("main_keyboard", u"\u307f", None))
        self.btn_n.setText(QCoreApplication.translate("main_keyboard", u"\u3093", None))
        self.btn_sa.setText(QCoreApplication.translate("main_keyboard", u"\u3055", None))
        self.btn_shi.setText(QCoreApplication.translate("main_keyboard", u"\u3057", None))
        self.btn_me.setText(QCoreApplication.translate("main_keyboard", u"\u3081", None))
        self.btn_e.setText(QCoreApplication.translate("main_keyboard", u"\u3048", None))
        self.btn_tsu.setText(QCoreApplication.translate("main_keyboard", u"\u3064", None))
        self.btn_ku.setText(QCoreApplication.translate("main_keyboard", u"\u304f", None))
        self.btn_clear.setText(QCoreApplication.translate("main_keyboard", u"\u00d7", None))
        self.btn_wa.setText(QCoreApplication.translate("main_keyboard", u"\u308f", None))
        self.btn_nu.setText(QCoreApplication.translate("main_keyboard", u"\u306c", None))
        self.btn_fu.setText(QCoreApplication.translate("main_keyboard", u"\u3075", None))
        self.btn_na.setText(QCoreApplication.translate("main_keyboard", u"\u306a", None))
    # retranslateUi

